services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
      PORT: 3000
    ports:
      - "30001:3000" # Custom security port for Backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      VITE_API_URL: http://localhost:30001
      VITE_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    ports:
      - "8080:80" # Custom security port for Frontend
    depends_on:
      - backend
